# Generated by Django 6.1.1 on 2026-10-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Em manutenção'), ('baixado', 'Baixado')], default='disponivel', max_length=20),
        ),
    ]
